name: Dockerhub Push for Cold Family Feud
on: push
jobs:
    build-container:
      name: Build Docker container image
      runs-on: ubuntu-latest
      steps:
        - name: Check
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Publish to Dockerhub
          uses: docker/build-push-action@v3
          with:
            tags: davbay1/cold-family-feud-docker:latest, ${{ github.run_number }}
            push: true
