name: Dockerhub Push for Cold Family Feud
on: push
jobs:
    build-container:
      name: Build Docker container image
      runs-on: ubuntu-latest
      steps:
        - name: Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Publish to Dockerhub
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: user/app:latest, ${{ github.run_number }}
