name: Dockerhub Push for Cold Family Feud
on: push
jobs:
    build-container:
      name: Build Docker container image
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Publish to Dockerhub
          uses: docker/build-push-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            repository: davbay1/cold-family-feud-unraid
            push: true
            tags: latest, ${{ github.run_number }}
